import type { Metadata } from 'next';
import { ThemeProvider } from './_components/theme-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/learn-pwa/icon-192x192.png', sizes: '48x48' },
      { url: '/learn-pwa/icon.svg', sizes: 'any', type: 'image/svg+xml' },
    ],
    apple: '/learn-pwa/icon-192x192.png',
  },
  manifest: '/learn-pwa/manifest.webmanifest',
  appleWebApp: {
    capable: true,
    title: 'ToDo',
    statusBarStyle: 'default',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, viewport-fit=cover"
        />
      </head>
      <body className="overflow-y-scroll pb-[env(safe-area-inset-bottom)]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
