import type { Metadata } from 'next';
import { ThemeProvider } from './_components/theme-provider';
import './globals.css';

export const metadata: Metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="icon" href="/icon-192x192.png" sizes="48x48" />
        <link
          rel="icon"
          href="/icon.svg"
          sizes="any"
          type="image/svg+xml"
        />
        <link rel="manifest" href="/manifest.json" />

        <link rel="apple-touch-icon" href="/icon-192x192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-title" content="TODO" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="default"
        ></meta>
        <meta
          name="viewport"
          content="initial-scale=1, viewport-fit=cover"
        />
      </head>
      <body className="pb-[env(safe-area-inset-bottom)]">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
